version: '2.3'

services:  
  tf-serving-client:
    container_name: tf-serving-client
    image: cputratama/tensorflow-serving-client:ver3
    networks:
      - tf_serving
    ports:
      - "5002:5002"
      - "8889:8889"
    environment:
      - TF_SERVER_NAME=tf-serving-server
      - TF_SERVER_PORT=9002
      - FLASK_SERVER_NAME=0.0.0.0
      - FLASK_SERVER_PORT=5002
      - FLASK_DEBUG=1        
networks:
  tf_serving:
    driver: bridge
